name: 'My Action'
description: 'This is a reusable action'

runs:
  using: 'composite'
  runs-on: ubuntu-latest
  steps:
    - name: 'Checkout'
      uses: actions/checkout@v3
    - name: 'Run Script'
      run: |
          echo "Hello world"