name: Check Pull Request Commits Authors
description: Validate pull request commits authors by email domain
inputs:
  EMAIL_DOMAIN:
    description: "Email domain to be checked. For example: email-domain.com"
    required: true
  GITHUB_REPOSITORY:
    description: "Github repository."
    required: true
  GITHUB_PULL_REQUEST:
    description: "Github pull request number."
    required: true
  GITHUB_TOKEN:
    description: "Github token to access the repository infos."
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Install jq'
      shell: bash
      run: sudo apt-get install -y jq
    - name: 'Parse GitHub Context'
      shell: bash
      run: |
          # Parse the pull request number using jq
          echo "${{inputs.GITHUB_PULL_REQUEST}} and ${{inputs.GITHUB_REPOSITORY}}"