name: 'My Action'
description: 'This is a reusable action'

runs:
  using: 'composite'
  steps:
    - name: 'Install jq'
      shell: bash
      run: sudo apt-get install -y jq
    - name: 'Parse GitHub Context'
      shell: bash
      run: |
          # Parse the pull request number using jq
          pull_request_number=$(echo "${GITHUB_CONTEXT}" | jq -r '.event.pull_request.number')
          echo "This is pull request number ${{pull_request_number}}"
          echo "${{ toJson(env.GITHUB_CONTEXT) }}"